language: go
go:
  - 1.14.x
install: make bootstrap
cache:
  - directories:
      - "$GOPATH/bin"
      - "$GOPATH/pkg"

script:
  - make lint
  - make test

branches:
  only:
    - master
    - "/^v([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:\\-(rc\\.[0-9]+)*)?$/"
