language: go
go:
- 1.10.x
install: make bootstrap
cache:
- directories:
  - "$GOPATH/bin"
  - "$GOPATH/pkg"
branches:
  only:
  - master
  - "/^v([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:\\-(rc\\.[0-9]+)*)?$/"
env:
  global:
